name: WageGlass CI

on:
  pull_request:
    branches: [main]

jobs:
  build-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install All Dependencies
        run: npm ci

      - name: Build Frontend
        working-directory: ./client
        run: npm run build

      - name: Build Backend
        working-directory: ./server
        run: npm run build
